services:
  564distech-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: 564distech-cloudflared
    restart: always
    network_mode: host
    env_file:
      - cloudflared.env
    command:
      - tunnel
      - --no-autoupdate
      - run
