#!/usr/bin/env bash
set -euo pipefail

service_name="564distech-cloudflared.service"
service_path="/etc/systemd/system/${service_name}"
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
docker_bin="$(command -v docker || true)"

if [[ ${EUID} -ne 0 ]]; then
  echo "Run this installer with sudo on 564Distech." >&2
  exit 1
fi

if ! command -v systemctl >/dev/null 2>&1; then
  echo "systemd is required to install the 564Distech autostart service." >&2
  exit 1
fi

if [[ -z "${docker_bin}" ]]; then
  echo "Docker is required before installing the 564Distech tunnel autostart service." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required before installing the 564Distech tunnel autostart service." >&2
  exit 1
fi

if [[ ! -f "${script_dir}/cloudflared.env" ]]; then
  cat >&2 <<'MSG'
Missing cloudflared.env.

Create it from cloudflared.env.example and set TUNNEL_TOKEN to the token
generated by Cloudflare Zero Trust for the 564Distech tunnel.
MSG
  exit 1
fi

if ! grep -Eq '^TUNNEL_TOKEN=.+$' "${script_dir}/cloudflared.env" || grep -q 'CHANGE_ME' "${script_dir}/cloudflared.env"; then
  echo "cloudflared.env exists, but TUNNEL_TOKEN is not set." >&2
  exit 1
fi

systemctl enable --now docker.service

cat >"${service_path}" <<UNIT
[Unit]
Description=564Distech Cloudflare Tunnel
Wants=network-online.target
After=network-online.target docker.service
Requires=docker.service

[Service]
Type=oneshot
WorkingDirectory=${script_dir}
ExecStart=${docker_bin} compose -f docker-compose.cloudflared.yml up -d --remove-orphans
ExecStop=${docker_bin} compose -f docker-compose.cloudflared.yml down
RemainAfterExit=yes
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable --now "${service_name}"
systemctl --no-pager status "${service_name}"
docker compose -f "${script_dir}/docker-compose.cloudflared.yml" ps
