#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}"

origin="${DISTECH_564_ORIGIN:-http://127.0.0.1/}"

if [[ ! -f cloudflared.env ]]; then
  cat >&2 <<'MSG'
Missing cloudflared.env.

Create it from cloudflared.env.example and set TUNNEL_TOKEN to the token
generated by Cloudflare Zero Trust for the 564Distech tunnel.
MSG
  exit 1
fi

if ! grep -Eq '^TUNNEL_TOKEN=.+$' cloudflared.env || grep -q 'CHANGE_ME' cloudflared.env; then
  cat >&2 <<'MSG'
cloudflared.env exists, but TUNNEL_TOKEN is not set.
MSG
  exit 1
fi

if ! curl -fsS --max-time 5 "${origin}" >/dev/null; then
  cat >&2 <<MSG
The 564Distech controller origin is not responding at ${origin}.
Start the controller UI or set DISTECH_564_ORIGIN before launching the tunnel.
MSG
  exit 1
fi

docker compose -f docker-compose.cloudflared.yml pull
docker compose -f docker-compose.cloudflared.yml up -d
docker compose -f docker-compose.cloudflared.yml ps
