#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}"

if [[ ! -f cloudflared.env ]]; then
  cat >&2 <<'MSG'
Missing cloudflared.env.

Create it from cloudflared.env.example and set TUNNEL_TOKEN to the token
generated by Cloudflare Zero Trust for the MD2Service tunnel.
MSG
  exit 1
fi

if ! grep -Eq '^TUNNEL_TOKEN=.+$' cloudflared.env || grep -q 'CHANGE_ME' cloudflared.env; then
  cat >&2 <<'MSG'
cloudflared.env exists, but TUNNEL_TOKEN is not set.
MSG
  exit 1
fi

if ! curl -fsS --max-time 5 http://127.0.0.1:1881/ >/dev/null; then
  cat >&2 <<'MSG'
The MD2Service origin is not responding at http://127.0.0.1:1881/.
Start the Systems service before launching the Cloudflare tunnel.
MSG
  exit 1
fi

docker compose -f docker-compose.cloudflared.yml pull
docker compose -f docker-compose.cloudflared.yml up -d
docker compose -f docker-compose.cloudflared.yml ps
